<?php
/**
 * BackWPup Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Backwpup
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Backwpup();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //BackWPup Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_backwpup_capabilities']);
    }

    /**
     * BackWPup Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_backwpup_capabilities($plugin_caps)
    {

        if (defined('REPLACE_WITH_PLUGIN_VERSION_CONSTANT')) {
            $plugin_caps['BackWPup'] = apply_filters(
                'cme_backwpup_capabilities',
                [
                    'backwpup',
                    'backwpup_backups',
                    'backwpup_backups_delete',
                    'backwpup_backups_download',
                    'backwpup_jobs',
                    'backwpup_jobs_edit',
                    'backwpup_jobs_start',
                    'backwpup_logs',
                    'backwpup_logs_delete',
                    'backwpup_restore',
                    'backwpup_settings'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Backwpup::instance();
?>
