<?php
/**
 * BetterDocs Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Betterdocs
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Betterdocs();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //BetterDocs Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_betterdocs_capabilities']);
    }

    /**
     * BetterDocs Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_betterdocs_capabilities($plugin_caps)
    {

        if (defined('BETTERDOCS_PLUGIN_FILE')) {
            $plugin_caps['BetterDocs'] = apply_filters(
                'cme_betterdocs_capabilities',
                [
                    'delete_doc_terms',
                    'delete_docs',
                    'delete_knowledge_base_terms',
                    'delete_others_docs',
                    'delete_private_docs',
                    'delete_published_docs',
                    'edit_doc_terms',
                    'edit_docs',
                    'edit_docs_settings',
                    'edit_knowledge_base_terms',
                    'edit_others_docs',
                    'edit_private_docs',
                    'edit_published_docs',
                    'manage_doc_terms',
                    'manage_knowledge_base_terms',
                    'publish_docs',
                    'read_docs_analytics',
                    'read_private_docs'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Betterdocs::instance();
?>
