<?php
/**
 * BuddyPress Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Buddypress
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Buddypress();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //BuddyPress Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_buddypress_capabilities']);
    }

    /**
     * BuddyPress Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_buddypress_capabilities($plugin_caps)
    {

        if (defined('BP_REQUIRED_PHP_VERSION')) {
            $plugin_caps['BuddyPress'] = apply_filters(
                'cme_buddypress_capabilities',
                [
                    'bp_members_invitations_view_screens',
                    'bp_moderate'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Buddypress::instance();
?>
