/**
 * Fluent Forms Capabilities class.
 * Generated by Capabilities Extractor
 */
namespace PublishPress\Plugin_Capabilities;

class Fluent_Forms
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Fluent_Forms();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Fluent Forms Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_fluent_forms_capabilities']);
    }

    /**
     * Fluent Forms Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_fluent_forms_capabilities($plugin_caps)
    {

        if (defined('FLUENTFORM')) {
            $plugin_caps['Fluent Forms'] = apply_filters(
                'cme_fluent_forms_capabilities',
                [
                    'fluentform_dashboard_access',
                    'fluentform_entries_viewer',
                    'fluentform_forms_manager',
                    'fluentform_full_access',
                    'fluentform_manage_entries',
                    'fluentform_manage_payments',
                    'fluentform_settings_manager',
                    'fluentform_view_payments'
                ]
            );
        }

        return $plugin_caps;
    }
}

\PublishPress\Plugin_Capabilities\Fluent_Forms::instance();
