<?php
/**
 * Gravity Forms Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Gravity_Forms
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Gravity_Forms();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Gravity Forms Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_gravity_forms_capabilities']);
    }

    /**
     * Gravity Forms Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_gravity_forms_capabilities($plugin_caps)
    {

        if (defined('GF_LICENSE_KEY')) {
            $plugin_caps['Gravity Forms'] = apply_filters(
                'cme_gravity_forms_capabilities',
                [
                    'gform_full_access',
                    'gravityforms_api_settings',
                    'gravityforms_create_form',
                    'gravityforms_delete_entries',
                    'gravityforms_delete_forms',
                    'gravityforms_edit_entries',
                    'gravityforms_edit_entry_notes',
                    'gravityforms_edit_forms',
                    'gravityforms_edit_settings',
                    'gravityforms_export_entries',
                    'gravityforms_logging',
                    'gravityforms_preview_forms',
                    'gravityforms_system_status',
                    'gravityforms_uninstall',
                    'gravityforms_view_addons',
                    'gravityforms_view_entries',
                    'gravityforms_view_entry_notes',
                    'gravityforms_view_settings',
                    'gravityforms_view_updates'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Gravity_Forms::instance();
?>
