<?php
/**
 * LearnDash LMS Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Learndash_Lms
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Learndash_Lms();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //LearnDash LMS Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_learndash_lms_capabilities']);
    }

    /**
     * LearnDash LMS Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_learndash_lms_capabilities($plugin_caps)
    {

        if (defined('LEARNDASH_VERSION')) {
            $plugin_caps['LearnDash LMS'] = apply_filters(
                'cme_learndash_lms_capabilities',
                [
                    'delete_assignment',
                    'delete_course',
                    'delete_courses',
                    'delete_essays',
                    'delete_group',
                    'delete_groups',
                    'delete_others_assignments',
                    'delete_others_courses',
                    'delete_others_essays',
                    'delete_others_groups',
                    'delete_private_courses',
                    'delete_published_assignments',
                    'delete_published_courses',
                    'delete_published_essays',
                    'delete_published_groups',
                    'edit_assignment',
                    'edit_assignments',
                    'edit_courses',
                    'edit_essays',
                    'edit_groups',
                    'edit_others_assignments',
                    'edit_others_courses',
                    'edit_others_essays',
                    'edit_others_groups',
                    'edit_private_courses',
                    'edit_published_assignments',
                    'edit_published_courses',
                    'edit_published_essays',
                    'edit_published_groups',
                    'enroll_users',
                    'publish_assignments',
                    'publish_courses',
                    'publish_essays',
                    'publish_groups',
                    'read_assignment',
                    'read_course',
                    'read_essays',
                    'read_group',
                    'read_private_assignments',
                    'read_private_courses',
                    'read_private_essays',
                    'read_private_groups',
                    'wpProQuiz_add_quiz',
                    'wpProQuiz_change_settings',
                    'wpProQuiz_delete_quiz',
                    'wpProQuiz_edit_quiz',
                    'wpProQuiz_export',
                    'wpProQuiz_import',
                    'wpProQuiz_reset_statistics',
                    'wpProQuiz_show',
                    'wpProQuiz_show_statistics',
                    'wpProQuiz_toplist_edit'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Learndash_Lms::instance();
?>
