<?php
/**
 * Loco Translate Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Loco_Translate
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Loco_Translate();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Loco Translate Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_loco_translate_capabilities']);
    }

    /**
     * Loco Translate Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_loco_translate_capabilities($plugin_caps)
    {

        if (defined('LOCO_LANG_DIR')) {
            $plugin_caps['Loco Translate'] = apply_filters(
                'cme_loco_translate_capabilities',
                [
                    'loco_admin'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Loco_Translate::instance();
?>
