<?php
/**
 * MailPoet Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Mailpoet
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Mailpoet();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //MailPoet Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_mailpoet_capabilities']);
    }

    /**
     * MailPoet Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_mailpoet_capabilities($plugin_caps)
    {

        if (defined('REPLACE_WITH_PLUGIN_VERSION_CONSTANT')) {
            $plugin_caps['MailPoet'] = apply_filters(
                'cme_mailpoet_capabilities',
                [
                    'mailpoet_access_plugin_admin',
                    'mailpoet_manage_automations',
                    'mailpoet_manage_emails',
                    'mailpoet_manage_features',
                    'mailpoet_manage_forms',
                    'mailpoet_manage_segments',
                    'mailpoet_manage_settings',
                    'mailpoet_manage_subscribers'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Mailpoet::instance();
?>
