<?php
/**
 * Query Monitor Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class publishpress_capabilities_query_monitor
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new publishpress_capabilities_query_monitor();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Query Monitor Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_query_monitor_capabilities']);
    }

    /**
     * Query Monitor Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_query_monitor_capabilities($plugin_caps)
    {

        if (defined('QM_VERSION')) {
            $plugin_caps['Query Monitor'] = apply_filters(
                'cme_query_monitor_capabilities',
                [
                    'view_query_monitor'
                ]
            );
        }

        return $plugin_caps;
    }
}
publishpress_capabilities_query_monitor::instance();
?>
