<?php
/**
 * Site Kit by Google Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class Publishpress_Capabilities_Site_Kit_By_Google
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Publishpress_Capabilities_Site_Kit_By_Google();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Site Kit by Google Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_site_kit_by_google_capabilities']);
    }

    /**
     * Site Kit by Google Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_site_kit_by_google_capabilities($plugin_caps)
    {

        if (defined('GOOGLESITEKIT_VERSION')) {
            $plugin_caps['Site Kit by Google'] = apply_filters(
                'cme_site_kit_by_google_capabilities',
                [
                    'googlesitekit_authenticate',
                    'googlesitekit_manage_options',
                    'googlesitekit_setup',
                    'googlesitekit_view_dashboard',
                    'googlesitekit_view_wp_dashboard_widget'
                ]
            );
        }

        return $plugin_caps;
    }
}
Publishpress_Capabilities_Site_Kit_By_Google::instance();
?>
