<?php
/**
 * Strong Testimonials Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class publishpress_capabilities_strong_testimonials
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new publishpress_capabilities_strong_testimonials();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Strong Testimonials Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_strong_testimonials_capabilities']);
    }

    /**
     * Strong Testimonials Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_strong_testimonials_capabilities($plugin_caps)
    {

        if (defined('WPMTST_VERSION')) {
            $plugin_caps['Strong Testimonials'] = apply_filters(
                'cme_strong_testimonials_capabilities',
                [
                    'strong_testimonials_about',
                    'strong_testimonials_fields',
                    'strong_testimonials_options',
                    'strong_testimonials_views'
                ]
            );
        }

        return $plugin_caps;
    }
}
publishpress_capabilities_strong_testimonials::instance();
?>
