<?php
/**
 * Wordfence Security Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class publishpress_capabilities_wordfence_security
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new publishpress_capabilities_wordfence_security();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Wordfence Security Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_wordfence_security_capabilities']);
    }

    /**
     * Wordfence Security Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_wordfence_security_capabilities($plugin_caps)
    {

        if (defined('WORDFENCE_VERSION')) {
            $plugin_caps['Wordfence Security'] = apply_filters(
                'cme_wordfence_security_capabilities',
                [
                    'wf2fa_activate_2fa_others',
                    'wf2fa_activate_2fa_self',
                    'wf2fa_manage_settings'
                ]
            );
        }

        return $plugin_caps;
    }
}
publishpress_capabilities_wordfence_security::instance();
?>
