<?php
/**
 * Yoast Duplicate Post Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class publishpress_capabilities_yoast_duplicate_post
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new publishpress_capabilities_yoast_duplicate_post();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Yoast Duplicate Post Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_yoast_duplicate_post_capabilities']);
    }

    /**
     * Yoast Duplicate Post Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_yoast_duplicate_post_capabilities($plugin_caps)
    {

        if (defined('DUPLICATE_POST_FILE')) {
            $plugin_caps['Yoast Duplicate Post'] = apply_filters(
                'cme_yoast_duplicate_post_capabilities',
                [
                    'copy_posts'
                ]
            );
        }

        return $plugin_caps;
    }
}
publishpress_capabilities_yoast_duplicate_post::instance();
?>
