<?php
/**
 * Yoast SEO Capabilities class.
 *
 * Generated by Capabilities Extractor
 */
class publishpress_capabilities_yoast_seo
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new publishpress_capabilities_yoast_seo();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Yoast SEO Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_yoast_seo_capabilities']);
    }

    /**
     * Yoast SEO Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_yoast_seo_capabilities($plugin_caps)
    {

        if (defined('WPSEO_FILE')) {
            $plugin_caps['Yoast SEO'] = apply_filters(
                'cme_yoast_seo_capabilities',
                [
                    'view_site_health_checks',
                    'wpseo_bulk_edit',
                    'wpseo_edit_advanced_metadata',
                    'wpseo_manage_options'
                ]
            );
        }

        return $plugin_caps;
    }
}
publishpress_capabilities_yoast_seo::instance();
?>
