/**
 * Yoast SEO Capabilities class.
 * Generated by Capabilities Extractor
 */
namespace PublishPress\Plugin_Capabilities;

class Yoast_SEO
{
    private static $instance = null;

    public static function instance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new Yoast_SEO();
        }

        return self::$instance;
    }

    public function __construct()
    {
        //Yoast SEO Capabilities
        add_filter('cme_plugin_capabilities', [$this, 'cme_yoast_seo_capabilities']);
    }

    /**
     * Yoast SEO Capabilities
     *
     * @param array $plugin_caps
     * 
     * @return array
     */
    public function cme_yoast_seo_capabilities($plugin_caps)
    {

        if (defined('WPSEO_FILE')) {
            $plugin_caps['Yoast SEO'] = apply_filters(
                'cme_yoast_seo_capabilities',
                [
                    'view_site_health_checks',
                    'wpseo_bulk_edit',
                    'wpseo_edit_advanced_metadata'
                ]
            );
        }

        return $plugin_caps;
    }
}

\PublishPress\Plugin_Capabilities\Yoast_SEO::instance();
